
package com.akmozo.webservice.orchestrateur;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "api", targetNamespace = "http://orchestrateur.webservice.akmozo.com/", wsdlLocation = "http://localhost:80/orchestrateur-0.1/api/Orchestrateur?wsdl")
public class Api
    extends Service
{

    private final static URL API_WSDL_LOCATION;
    private final static WebServiceException API_EXCEPTION;
    private final static QName API_QNAME = new QName("http://orchestrateur.webservice.akmozo.com/", "api");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:80/orchestrateur-0.1/api/Orchestrateur?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        API_WSDL_LOCATION = url;
        API_EXCEPTION = e;
    }

    public Api() {
        super(__getWsdlLocation(), API_QNAME);
    }

    public Api(WebServiceFeature... features) {
        super(__getWsdlLocation(), API_QNAME, features);
    }

    public Api(URL wsdlLocation) {
        super(wsdlLocation, API_QNAME);
    }

    public Api(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, API_QNAME, features);
    }

    public Api(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Api(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IOrchestrateur
     */
    @WebEndpoint(name = "OrchestrateurPort")
    public IOrchestrateur getOrchestrateurPort() {
        return super.getPort(new QName("http://orchestrateur.webservice.akmozo.com/", "OrchestrateurPort"), IOrchestrateur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrchestrateur
     */
    @WebEndpoint(name = "OrchestrateurPort")
    public IOrchestrateur getOrchestrateurPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://orchestrateur.webservice.akmozo.com/", "OrchestrateurPort"), IOrchestrateur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (API_EXCEPTION!= null) {
            throw API_EXCEPTION;
        }
        return API_WSDL_LOCATION;
    }

}
