
package com.akmozo.webservice.orchestrateur;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.akmozo.webservice.concierges.DetailsReservation;
import com.akmozo.webservice.paiement.DonneesPaiement;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOrchestrateur", targetNamespace = "http://orchestrateur.webservice.akmozo.com/")
@XmlSeeAlso({
    com.akmozo.webservice.concierges.ObjectFactory.class,
    com.akmozo.webservice.orchestrateur.ObjectFactory.class,
    com.akmozo.webservice.paiement.ObjectFactory.class
})
public interface IOrchestrateur {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payerEtReserverAgent", targetNamespace = "http://orchestrateur.webservice.akmozo.com/", className = "com.akmozo.webservice.orchestrateur.PayerEtReserverAgent")
    @ResponseWrapper(localName = "payerEtReserverAgentResponse", targetNamespace = "http://orchestrateur.webservice.akmozo.com/", className = "com.akmozo.webservice.orchestrateur.PayerEtReserverAgentResponse")
    public boolean payerEtReserverAgent(
        @WebParam(name = "arg0", targetNamespace = "")
        DonneesPaiement arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        DetailsReservation arg1);

}
